title: Esther Rowena Louise Music
markdown: kramdown
baseurl: /estherrowenalouisemusic
collections:
  pages:
    output: true
    permalink: /:name
exclude:
  - "Gemfile*"
  - "README.txt"
  - "redirects.json"
  - "serve.sh"
plugins:
  - jekyll-redirect-from